### PR TITLE
Cmake fixes for Dyninst dependencies

### PR DESCRIPTION
**Pull request by hainest**

### CODE REVIEW

**Comment by hainest** [comment]
The public headers of SymtabAPI require Boost, but Dyninst doesn't correctly export the include dependencies it uses, so we have to do it manually here. I have a feeling this worked fine in your container because Boost was in a system directory. We should double-check this still works in your container before merging!

**Comment by vsoch** [comment]
It looks like boost is a dependency -> https://github.com/spack/spack/blob/95ad5b882c990971e74d04261a665ba680f7c4be/var/spack/repos/builtin/packages/dyninst/package.py#L41, so we know it's in the container somewhere! Let me pull this branch and test, and I'll update here with what I find!

**Comment by vsoch** [comment]
It works without a hitch!  Woot woot! Let's merge!

**Comment by vsoch** [comment]
I am squashing and merging so you should update your main with this new commit.

**Pull request merged**
